<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\HomepageSection;

class HomepageSectionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sections = [
            [
                'name' => 'Main Slider',
                'slug' => 'main-slider',
                'description' => 'Hero/banner carousel for the homepage top.',
                'icon' => 'mdi mdi-image-multiple',
                'is_system' => true, 'is_active' => true,
                'default_columns' => 'col-sm-12', 'default_order' => 1,
                'settings_schema' => json_encode(['autoplay' => true, 'autoplay_speed' => 3000, 'slider_count' => 5]),
            ],
            [
                'name' => 'Sidebar Categories',
                'slug' => 'sidebar-categories',
                'description' => 'Left sidebar category navigation menu.',
                'icon' => 'mdi mdi-menu',
                'is_system' => true, 'is_active' => true,
                'default_columns' => 'col-sm-3', 'default_order' => 2,
                'settings_schema' => json_encode(['show_icons' => true, 'expand_on_hover' => true]),
            ],
            [
                'name' => 'Top Categories',
                'slug' => 'top-categories',
                'description' => 'Category icons carousel / grid display.',
                'icon' => 'mdi mdi-shape',
                'is_system' => true, 'is_active' => true,
                'default_columns' => 'col-sm-12', 'default_order' => 3,
                'settings_schema' => json_encode(['layout' => 'carousel', 'max_items' => 12]),
            ],
            [
                'name' => 'Flash Sales',
                'slug' => 'flash-sales',
                'description' => 'Timed discount products with countdown timer.',
                'icon' => 'mdi mdi-flash',
                'is_system' => true, 'is_active' => true,
                'default_columns' => 'col-sm-12', 'default_order' => 4,
                'settings_schema' => json_encode(['show_timer' => true, 'max_items' => 12, 'carousel' => true]),
            ],
            [
                'name' => 'Hot Deals',
                'slug' => 'hot-deals',
                'description' => 'Featured products section with hot deal timer.',
                'icon' => 'mdi mdi-fire',
                'is_system' => true, 'is_active' => true,
                'default_columns' => 'col-sm-12', 'default_order' => 5,
                'settings_schema' => json_encode(['show_timer' => true, 'max_items' => 12, 'carousel' => true]),
            ],
            [
                'name' => 'All Products',
                'slug' => 'all-products',
                'description' => 'Random product grid showing all products.',
                'icon' => 'mdi mdi-view-grid',
                'is_system' => true, 'is_active' => true,
                'default_columns' => 'col-sm-12', 'default_order' => 6,
                'settings_schema' => json_encode(['max_items' => 14, 'randomize' => true]),
            ],
            [
                'name' => 'Category-wise Products',
                'slug' => 'category-products',
                'description' => 'Products grouped by category with view more links.',
                'icon' => 'mdi mdi-shape-plus',
                'is_system' => true, 'is_active' => true,
                'default_columns' => 'col-sm-12', 'default_order' => 7,
                'settings_schema' => json_encode(['max_products_per_category' => 12]),
            ],
            [
                'name' => 'Slider Bottom Ads',
                'slug' => 'slider-bottom-ads',
                'description' => 'Banner advertisements displayed below the slider.',
                'icon' => 'mdi mdi-image',
                'is_system' => true, 'is_active' => true,
                'default_columns' => 'col-sm-12', 'default_order' => 8,
                'settings_schema' => json_encode(['max_ads' => 3]),
            ],
            [
                'name' => 'Campaign Ads',
                'slug' => 'campaign-ads',
                'description' => 'Promotional campaign banners.',
                'icon' => 'mdi mdi-bullhorn',
                'is_system' => true, 'is_active' => true,
                'default_columns' => 'col-sm-12', 'default_order' => 9,
                'settings_schema' => json_encode(['max_ads' => 3]),
            ],
            [
                'name' => 'Brands',
                'slug' => 'brands',
                'description' => 'Brand logo grid or carousel.',
                'icon' => 'mdi mdi-domain',
                'is_system' => true, 'is_active' => true,
                'default_columns' => 'col-sm-12', 'default_order' => 10,
                'settings_schema' => json_encode(['layout' => 'grid', 'max_brands' => 12]),
            ],
            [
                'name' => 'Latest Blogs',
                'slug' => 'latest-blogs',
                'description' => 'Recent blog post cards with images and excerpts.',
                'icon' => 'mdi mdi-post',
                'is_system' => true, 'is_active' => true,
                'default_columns' => 'col-sm-12', 'default_order' => 11,
                'settings_schema' => json_encode(['max_posts' => 3, 'show_excerpt' => true]),
            ],
            [
                'name' => 'Customer Reviews',
                'slug' => 'customer-reviews',
                'description' => 'Customer testimonial / review image carousel.',
                'icon' => 'mdi mdi-star-circle',
                'is_system' => true, 'is_active' => true,
                'default_columns' => 'col-sm-12', 'default_order' => 12,
                'settings_schema' => json_encode(['max_reviews' => 10, 'autoplay' => true]),
            ],
            [
                'name' => 'Footer Top Ads',
                'slug' => 'footer-top-ads',
                'description' => 'Banners displayed above the footer.',
                'icon' => 'mdi mdi-image-footer',
                'is_system' => true, 'is_active' => true,
                'default_columns' => 'col-sm-12', 'default_order' => 13,
                'settings_schema' => json_encode(['max_ads' => 3]),
            ],
            [
                'name' => 'Hot Deal Banner',
                'slug' => 'hot-deal-banner',
                'description' => 'Full-width promotional banner for hot deals.',
                'icon' => 'mdi mdi-sale',
                'is_system' => true, 'is_active' => true,
                'default_columns' => 'col-sm-12', 'default_order' => 14,
                'settings_schema' => json_encode(['link' => true]),
            ],
            [
                'name' => 'Event Section',
                'slug' => 'event-section',
                'description' => 'Special announcement or event highlight bar.',
                'icon' => 'mdi mdi-calendar-star',
                'is_system' => true, 'is_active' => true,
                'default_columns' => 'col-sm-12', 'default_order' => 15,
                'settings_schema' => json_encode(['show_cta' => true]),
            ],
            [
                'name' => 'Brand Introduction',
                'slug' => 'brand-intro',
                'description' => 'Brand story section with image and description.',
                'icon' => 'mdi mdi-information',
                'is_system' => true, 'is_active' => true,
                'default_columns' => 'col-sm-12', 'default_order' => 16,
                'settings_schema' => json_encode(['show_image' => true]),
            ],
            [
                'name' => 'New Arrival Tiles',
                'slug' => 'new-arrivals',
                'description' => 'Category tile grid for new arrivals.',
                'icon' => 'mdi mdi-new-box',
                'is_system' => true, 'is_active' => true,
                'default_columns' => 'col-sm-12', 'default_order' => 17,
                'settings_schema' => json_encode(['max_tiles' => 12]),
            ],
            [
                'name' => 'Home Ads',
                'slug' => 'home-ads',
                'description' => '2-column banner advertisement grid.',
                'icon' => 'mdi mdi-image-area',
                'is_system' => true, 'is_active' => true,
                'default_columns' => 'col-sm-12', 'default_order' => 18,
                'settings_schema' => json_encode(['columns' => 2, 'max_ads' => 2]),
            ],
            [
                'name' => 'Home Ads 2',
                'slug' => 'home-ads-2',
                'description' => '3-column banner advertisement grid.',
                'icon' => 'mdi mdi-image-area',
                'is_system' => true, 'is_active' => true,
                'default_columns' => 'col-sm-12', 'default_order' => 19,
                'settings_schema' => json_encode(['columns' => 3, 'max_ads' => 6]),
            ],
            [
                'name' => 'Featured Shops',
                'slug' => 'featured-shops',
                'description' => 'Vendor shop cards with logo, banner rating and visit button.',
                'icon' => 'mdi mdi-store',
                'is_system' => true, 'is_active' => true,
                'default_columns' => 'col-sm-12', 'default_order' => 20,
                'settings_schema' => json_encode(['max_shops' => 12]),
            ],
            [
                'name' => 'Limited Time Offers',
                'slug' => 'limited-offers',
                'description' => 'Special limited-time offer banners.',
                'icon' => 'mdi mdi-clock-fast',
                'is_system' => true, 'is_active' => true,
                'default_columns' => 'col-sm-12', 'default_order' => 21,
                'settings_schema' => json_encode(['max_offers' => 4]),
            ],
            [
                'name' => 'Extra Discount',
                'slug' => 'extra-discount',
                'description' => 'Today\'s special deal / extra discount banner.',
                'icon' => 'mdi mdi-percent',
                'is_system' => true, 'is_active' => true,
                'default_columns' => 'col-sm-12', 'default_order' => 22,
                'settings_schema' => json_encode(['show_timer' => false]),
            ],
            [
                'name' => 'Affiliate Section',
                'slug' => 'affiliate-section',
                'description' => 'Reseller program / earn money call-to-action.',
                'icon' => 'mdi mdi-handshake',
                'is_system' => true, 'is_active' => true,
                'default_columns' => 'col-sm-12', 'default_order' => 23,
                'settings_schema' => json_encode(['show_cta' => true]),
            ],
            [
                'name' => 'Client Logos',
                'slug' => 'client-logos',
                'description' => 'Partner/client logo carousel.',
                'icon' => 'mdi mdi-account-group',
                'is_system' => true, 'is_active' => true,
                'default_columns' => 'col-sm-12', 'default_order' => 24,
                'settings_schema' => json_encode(['max_logos' => 20]),
            ],
            [
                'name' => 'Work With Us',
                'slug' => 'work-with-us',
                'description' => 'Call-to-action section for partners and affiliates.',
                'icon' => 'mdi mdi-briefcase',
                'is_system' => true, 'is_active' => true,
                'default_columns' => 'col-sm-12', 'default_order' => 25,
                'settings_schema' => json_encode(['show_partner_logo' => true]),
            ],
            [
                'name' => 'Product Grid',
                'slug' => 'product-grid',
                'description' => 'Custom product selection grid with manual product pick.',
                'icon' => 'mdi mdi-cart',
                'is_system' => false, 'is_active' => true,
                'default_columns' => 'col-sm-12', 'default_order' => 26,
                'settings_schema' => json_encode(['product_ids' => [], 'max_items' => 12]),
            ],
            [
                'name' => 'Video Section',
                'slug' => 'video-section',
                'description' => 'Embedded video or video promotion section.',
                'icon' => 'mdi mdi-video',
                'is_system' => false, 'is_active' => true,
                'default_columns' => 'col-sm-12', 'default_order' => 27,
                'settings_schema' => json_encode(['video_url' => '', 'autoplay' => false]),
            ],
            [
                'name' => 'Custom HTML',
                'slug' => 'custom-html',
                'description' => 'Raw HTML block for custom content.',
                'icon' => 'mdi mdi-code-tags',
                'is_system' => false, 'is_active' => true,
                'default_columns' => 'col-sm-12', 'default_order' => 28,
                'settings_schema' => json_encode(['html_content' => '']),
            ],
        ];

        foreach ($sections as $section) {
            HomepageSection::create($section);
        }
    }
}
