<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Theme;

class ThemeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $themes = [
            [
                'name'          => 'Ocean Blue',
                'slug'          => 'ocean-blue',
                'description'   => 'A professional blue theme perfect for corporate e-commerce stores.',
                'is_default'    => true,
                'is_active'     => true,
                'primary_color' => '#0d6efd', 'secondary_color' => '#0b5ed7', 'accent_color' => '#ff6a00',
                'text_color' => '#212529', 'heading_color' => '#111111', 'body_bg_color' => '#ffffff',
                'header_bg_color' => '#ffffff', 'header_text_color' => '#212529',
                'footer_bg_color' => '#1a1a1a', 'footer_text_color' => '#cccccc',
                'copyright_bg_color' => '#000000', 'copyright_text_color' => '#ffffff',
                'button_bg_color' => '#0d6efd', 'button_text_color' => '#ffffff', 'button_hover_bg_color' => '#0b5ed7',
                'border_color' => '#dee2e6', 'sale_badge_bg' => '#dc3545', 'sale_badge_text' => '#ffffff',
                'font_family' => "'Roboto', sans-serif", 'heading_font' => "'Jost', sans-serif",
                'body_font_size' => '14px', 'heading_font_weight' => '700',
                'layout_style' => 'contained', 'border_radius' => '8px', 'card_shadow' => '0 2px 8px rgba(0,0,0,0.08)',
            ],
            [
                'name'          => 'Forest Green',
                'slug'          => 'forest-green',
                'description'   => 'A nature-inspired green theme for eco-friendly and organic brands.',
                'is_default'    => false,
                'is_active'     => true,
                'primary_color' => '#198754', 'secondary_color' => '#157347', 'accent_color' => '#ffc107',
                'text_color' => '#212529', 'heading_color' => '#111111', 'body_bg_color' => '#ffffff',
                'header_bg_color' => '#ffffff', 'header_text_color' => '#212529',
                'footer_bg_color' => '#1a3a2a', 'footer_text_color' => '#d4edda',
                'copyright_bg_color' => '#0d2818', 'copyright_text_color' => '#ffffff',
                'button_bg_color' => '#198754', 'button_text_color' => '#ffffff', 'button_hover_bg_color' => '#157347',
                'border_color' => '#d4edda', 'sale_badge_bg' => '#dc3545', 'sale_badge_text' => '#ffffff',
                'font_family' => "'Roboto', sans-serif", 'heading_font' => "'Jost', sans-serif",
                'body_font_size' => '14px', 'heading_font_weight' => '700',
                'layout_style' => 'contained', 'border_radius' => '10px', 'card_shadow' => '0 2px 8px rgba(0,0,0,0.08)',
            ],
            [
                'name'          => 'Crimson Red',
                'slug'          => 'crimson-red',
                'description'   => 'A bold, energetic red theme for high-impact brands.',
                'is_default'    => false,
                'is_active'     => true,
                'primary_color' => '#dc3545', 'secondary_color' => '#bb2d3b', 'accent_color' => '#fd7e14',
                'text_color' => '#212529', 'heading_color' => '#111111', 'body_bg_color' => '#ffffff',
                'header_bg_color' => '#ffffff', 'header_text_color' => '#212529',
                'footer_bg_color' => '#2d0a0e', 'footer_text_color' => '#f8d7da',
                'copyright_bg_color' => '#1a0507', 'copyright_text_color' => '#ffffff',
                'button_bg_color' => '#dc3545', 'button_text_color' => '#ffffff', 'button_hover_bg_color' => '#bb2d3b',
                'border_color' => '#f5c6cb', 'sale_badge_bg' => '#dc3545', 'sale_badge_text' => '#ffffff',
                'font_family' => "'Roboto', sans-serif", 'heading_font' => "'Jost', sans-serif",
                'body_font_size' => '14px', 'heading_font_weight' => '700',
                'layout_style' => 'contained', 'border_radius' => '6px', 'card_shadow' => '0 2px 8px rgba(0,0,0,0.08)',
            ],
            [
                'name'          => 'Amber Sunset',
                'slug'          => 'amber-sunset',
                'description'   => 'A warm, playful orange theme perfect for creative brands.',
                'is_default'    => false,
                'is_active'     => true,
                'primary_color' => '#ff6a00', 'secondary_color' => '#e05d00', 'accent_color' => '#ffc107',
                'text_color' => '#212529', 'heading_color' => '#111111', 'body_bg_color' => '#fef9f0',
                'header_bg_color' => '#ffffff', 'header_text_color' => '#212529',
                'footer_bg_color' => '#2d1a00', 'footer_text_color' => '#ffe0b2',
                'copyright_bg_color' => '#1a0f00', 'copyright_text_color' => '#ffffff',
                'button_bg_color' => '#ff6a00', 'button_text_color' => '#ffffff', 'button_hover_bg_color' => '#e05d00',
                'border_color' => '#ffe0b2', 'sale_badge_bg' => '#dc3545', 'sale_badge_text' => '#ffffff',
                'font_family' => "'Roboto', sans-serif", 'heading_font' => "'Jost', sans-serif",
                'body_font_size' => '14px', 'heading_font_weight' => '700',
                'layout_style' => 'contained', 'border_radius' => '12px', 'card_shadow' => '0 4px 12px rgba(255,106,0,0.12)',
            ],
            [
                'name'          => 'Royal Purple',
                'slug'          => 'royal-purple',
                'description'   => 'A luxurious purple theme for premium and high-end brands.',
                'is_default'    => false,
                'is_active'     => true,
                'primary_color' => '#6f42c1', 'secondary_color' => '#5a32a3', 'accent_color' => '#e83e8c',
                'text_color' => '#212529', 'heading_color' => '#111111', 'body_bg_color' => '#ffffff',
                'header_bg_color' => '#ffffff', 'header_text_color' => '#212529',
                'footer_bg_color' => '#2d1b4e', 'footer_text_color' => '#e0d4f5',
                'copyright_bg_color' => '#1a0f2e', 'copyright_text_color' => '#ffffff',
                'button_bg_color' => '#6f42c1', 'button_text_color' => '#ffffff', 'button_hover_bg_color' => '#5a32a3',
                'border_color' => '#d4c5f0', 'sale_badge_bg' => '#e83e8c', 'sale_badge_text' => '#ffffff',
                'font_family' => "'Roboto', sans-serif", 'heading_font' => "'Playfair Display', serif",
                'body_font_size' => '14px', 'heading_font_weight' => '700',
                'layout_style' => 'contained', 'border_radius' => '8px', 'card_shadow' => '0 4px 16px rgba(111,66,193,0.15)',
            ],
            [
                'name'          => 'Midnight Dark',
                'slug'          => 'midnight-dark',
                'description'   => 'A sleek dark mode theme for modern, edgy brands.',
                'is_default'    => false,
                'is_active'     => true,
                'primary_color' => '#1a1a2e', 'secondary_color' => '#16213e', 'accent_color' => '#e94560',
                'text_color' => '#e0e0e0', 'heading_color' => '#ffffff', 'body_bg_color' => '#0f0f23',
                'header_bg_color' => '#1a1a2e', 'header_text_color' => '#e0e0e0',
                'footer_bg_color' => '#0a0a1a', 'footer_text_color' => '#8888aa',
                'copyright_bg_color' => '#050510', 'copyright_text_color' => '#666688',
                'button_bg_color' => '#e94560', 'button_text_color' => '#ffffff', 'button_hover_bg_color' => '#d63851',
                'border_color' => '#2a2a4e', 'sale_badge_bg' => '#e94560', 'sale_badge_text' => '#ffffff',
                'font_family' => "'Roboto', sans-serif", 'heading_font' => "'Jost', sans-serif",
                'body_font_size' => '14px', 'heading_font_weight' => '700',
                'layout_style' => 'full-width', 'border_radius' => '8px', 'card_shadow' => '0 2px 8px rgba(233,69,96,0.2)',
            ],
            [
                'name'          => 'Rose Pink',
                'slug'          => 'rose-pink',
                'description'   => 'An elegant pink theme for beauty, fashion, and feminine brands.',
                'is_default'    => false,
                'is_active'     => true,
                'primary_color' => '#e83e8c', 'secondary_color' => '#d63384', 'accent_color' => '#ff6a00',
                'text_color' => '#212529', 'heading_color' => '#111111', 'body_bg_color' => '#fff5f8',
                'header_bg_color' => '#ffffff', 'header_text_color' => '#212529',
                'footer_bg_color' => '#3d1a2e', 'footer_text_color' => '#f8d4e4',
                'copyright_bg_color' => '#2a0f1e', 'copyright_text_color' => '#ffffff',
                'button_bg_color' => '#e83e8c', 'button_text_color' => '#ffffff', 'button_hover_bg_color' => '#d63384',
                'border_color' => '#f5c6d6', 'sale_badge_bg' => '#e83e8c', 'sale_badge_text' => '#ffffff',
                'font_family' => "'Roboto', sans-serif", 'heading_font' => "'Playfair Display', serif",
                'body_font_size' => '14px', 'heading_font_weight' => '700',
                'layout_style' => 'contained', 'border_radius' => '12px', 'card_shadow' => '0 2px 8px rgba(232,62,140,0.1)',
            ],
            [
                'name'          => 'Teal Wave',
                'slug'          => 'teal-wave',
                'description'   => 'A fresh, modern teal theme for contemporary brands.',
                'is_default'    => false,
                'is_active'     => true,
                'primary_color' => '#20c997', 'secondary_color' => '#1ba87e', 'accent_color' => '#fd7e14',
                'text_color' => '#212529', 'heading_color' => '#111111', 'body_bg_color' => '#f5fffc',
                'header_bg_color' => '#ffffff', 'header_text_color' => '#212529',
                'footer_bg_color' => '#0d2b20', 'footer_text_color' => '#c4e8dc',
                'copyright_bg_color' => '#061a13', 'copyright_text_color' => '#ffffff',
                'button_bg_color' => '#20c997', 'button_text_color' => '#ffffff', 'button_hover_bg_color' => '#1ba87e',
                'border_color' => '#c4e8dc', 'sale_badge_bg' => '#fd7e14', 'sale_badge_text' => '#ffffff',
                'font_family' => "'Roboto', sans-serif", 'heading_font' => "'Jost', sans-serif",
                'body_font_size' => '14px', 'heading_font_weight' => '700',
                'layout_style' => 'contained', 'border_radius' => '8px', 'card_shadow' => '0 2px 8px rgba(32,201,151,0.12)',
            ],
            [
                'name'          => 'Golden Harvest',
                'slug'          => 'golden-harvest',
                'description'   => 'A premium gold-themed design for luxury and high-end stores.',
                'is_default'    => false,
                'is_active'     => true,
                'primary_color' => '#ffc107', 'secondary_color' => '#e0a800', 'accent_color' => '#dc3545',
                'text_color' => '#212529', 'heading_color' => '#111111', 'body_bg_color' => '#fffef5',
                'header_bg_color' => '#ffffff', 'header_text_color' => '#212529',
                'footer_bg_color' => '#2d2400', 'footer_text_color' => '#ffe082',
                'copyright_bg_color' => '#1a1500', 'copyright_text_color' => '#ffffff',
                'button_bg_color' => '#ffc107', 'button_text_color' => '#000000', 'button_hover_bg_color' => '#e0a800',
                'border_color' => '#ffe082', 'sale_badge_bg' => '#dc3545', 'sale_badge_text' => '#ffffff',
                'font_family' => "'Roboto', sans-serif", 'heading_font' => "'Playfair Display', serif",
                'body_font_size' => '14px', 'heading_font_weight' => '700',
                'layout_style' => 'contained', 'border_radius' => '8px', 'card_shadow' => '0 4px 16px rgba(255,193,7,0.15)',
            ],
            [
                'name'          => 'Slate Gray',
                'slug'          => 'slate-gray',
                'description'   => 'A clean, minimalist gray theme for modern and professional stores.',
                'is_default'    => false,
                'is_active'     => true,
                'primary_color' => '#6c757d', 'secondary_color' => '#5a6268', 'accent_color' => '#0d6efd',
                'text_color' => '#212529', 'heading_color' => '#111111', 'body_bg_color' => '#f8f9fa',
                'header_bg_color' => '#ffffff', 'header_text_color' => '#212529',
                'footer_bg_color' => '#343a40', 'footer_text_color' => '#ced4da',
                'copyright_bg_color' => '#212529', 'copyright_text_color' => '#adb5bd',
                'button_bg_color' => '#6c757d', 'button_text_color' => '#ffffff', 'button_hover_bg_color' => '#5a6268',
                'border_color' => '#dee2e6', 'sale_badge_bg' => '#dc3545', 'sale_badge_text' => '#ffffff',
                'font_family' => "'Roboto', sans-serif", 'heading_font' => "'Jost', sans-serif",
                'body_font_size' => '14px', 'heading_font_weight' => '500',
                'layout_style' => 'contained', 'border_radius' => '4px', 'card_shadow' => '0 1px 4px rgba(0,0,0,0.06)',
            ],
            [
                'name'          => 'Coral Reef',
                'slug'          => 'coral-reef',
                'description'   => 'A vibrant, cheerful coral theme for lively and fun brands.',
                'is_default'    => false,
                'is_active'     => true,
                'primary_color' => '#ff7f50', 'secondary_color' => '#e0673e', 'accent_color' => '#20c997',
                'text_color' => '#212529', 'heading_color' => '#111111', 'body_bg_color' => '#fff8f5',
                'header_bg_color' => '#ffffff', 'header_text_color' => '#212529',
                'footer_bg_color' => '#3d1a0f', 'footer_text_color' => '#ffd4c4',
                'copyright_bg_color' => '#2a0f08', 'copyright_text_color' => '#ffffff',
                'button_bg_color' => '#ff7f50', 'button_text_color' => '#ffffff', 'button_hover_bg_color' => '#e0673e',
                'border_color' => '#ffd4c4', 'sale_badge_bg' => '#20c997', 'sale_badge_text' => '#ffffff',
                'font_family' => "'Roboto', sans-serif", 'heading_font' => "'Jost', sans-serif",
                'body_font_size' => '14px', 'heading_font_weight' => '700',
                'layout_style' => 'contained', 'border_radius' => '10px', 'card_shadow' => '0 4px 12px rgba(255,127,80,0.15)',
            ],
            [
                'name'          => 'Navy Classic',
                'slug'          => 'navy-classic',
                'description'   => 'A corporate navy blue theme for authoritative and trusted brands.',
                'is_default'    => false,
                'is_active'     => true,
                'primary_color' => '#001f3f', 'secondary_color' => '#003366', 'accent_color' => '#ff6a00',
                'text_color' => '#e0e0e0', 'heading_color' => '#ffffff', 'body_bg_color' => '#f5f8fc',
                'header_bg_color' => '#001f3f', 'header_text_color' => '#ffffff',
                'footer_bg_color' => '#000d1a', 'footer_text_color' => '#8099b3',
                'copyright_bg_color' => '#00060d', 'copyright_text_color' => '#668099',
                'button_bg_color' => '#003366', 'button_text_color' => '#ffffff', 'button_hover_bg_color' => '#002244',
                'border_color' => '#cce0ff', 'sale_badge_bg' => '#ff6a00', 'sale_badge_text' => '#ffffff',
                'font_family' => "'Roboto', sans-serif", 'heading_font' => "'Jost', sans-serif",
                'body_font_size' => '14px', 'heading_font_weight' => '700',
                'layout_style' => 'contained', 'border_radius' => '6px', 'card_shadow' => '0 2px 8px rgba(0,31,63,0.1)',
            ],
            [
                'name'          => 'Lavender Dream',
                'slug'          => 'lavender-dream',
                'description'   => 'A soft, calming lavender theme for gentle and caring brands.',
                'is_default'    => false,
                'is_active'     => true,
                'primary_color' => '#9b59b6', 'secondary_color' => '#8e44ad', 'accent_color' => '#f39c12',
                'text_color' => '#2c3e50', 'heading_color' => '#1a1a2e', 'body_bg_color' => '#faf5ff',
                'header_bg_color' => '#ffffff', 'header_text_color' => '#2c3e50',
                'footer_bg_color' => '#2d1b4e', 'footer_text_color' => '#d4c5f0',
                'copyright_bg_color' => '#1a0f2e', 'copyright_text_color' => '#ffffff',
                'button_bg_color' => '#9b59b6', 'button_text_color' => '#ffffff', 'button_hover_bg_color' => '#8e44ad',
                'border_color' => '#d4c5f0', 'sale_badge_bg' => '#f39c12', 'sale_badge_text' => '#ffffff',
                'font_family' => "'Roboto', sans-serif", 'heading_font' => "'Playfair Display', serif",
                'body_font_size' => '14px', 'heading_font_weight' => '600',
                'layout_style' => 'contained', 'border_radius' => '12px', 'card_shadow' => '0 4px 12px rgba(155,89,182,0.1)',
            ],
            [
                'name'          => 'Cherry Blossom',
                'slug'          => 'cherry-blossom',
                'description'   => 'A delicate, gentle pink theme inspired by cherry blossoms.',
                'is_default'    => false,
                'is_active'     => true,
                'primary_color' => '#ffb7c5', 'secondary_color' => '#ff9eb5', 'accent_color' => '#ff6b8a',
                'text_color' => '#5a3d4a', 'heading_color' => '#3d2a33', 'body_bg_color' => '#fff9fa',
                'header_bg_color' => '#ffffff', 'header_text_color' => '#5a3d4a',
                'footer_bg_color' => '#3d1a24', 'footer_text_color' => '#ffd4dc',
                'copyright_bg_color' => '#2a0f16', 'copyright_text_color' => '#ffffff',
                'button_bg_color' => '#ffb7c5', 'button_text_color' => '#5a3d4a', 'button_hover_bg_color' => '#ff9eb5',
                'border_color' => '#ffd4dc', 'sale_badge_bg' => '#ff6b8a', 'sale_badge_text' => '#ffffff',
                'font_family' => "'Roboto', sans-serif", 'heading_font' => "'Playfair Display', serif",
                'body_font_size' => '14px', 'heading_font_weight' => '600',
                'layout_style' => 'contained', 'border_radius' => '16px', 'card_shadow' => '0 4px 12px rgba(255,183,197,0.2)',
            ],
            [
                'name'          => 'Emerald City',
                'slug'          => 'emerald-city',
                'description'   => 'A rich, prosperous green theme for growth-focused brands.',
                'is_default'    => false,
                'is_active'     => true,
                'primary_color' => '#2ecc71', 'secondary_color' => '#27ae60', 'accent_color' => '#f1c40f',
                'text_color' => '#212529', 'heading_color' => '#111111', 'body_bg_color' => '#f5fff8',
                'header_bg_color' => '#ffffff', 'header_text_color' => '#212529',
                'footer_bg_color' => '#0d2818', 'footer_text_color' => '#a3d9b1',
                'copyright_bg_color' => '#061a0f', 'copyright_text_color' => '#ffffff',
                'button_bg_color' => '#2ecc71', 'button_text_color' => '#ffffff', 'button_hover_bg_color' => '#27ae60',
                'border_color' => '#a3d9b1', 'sale_badge_bg' => '#f1c40f', 'sale_badge_text' => '#000000',
                'font_family' => "'Roboto', sans-serif", 'heading_font' => "'Jost', sans-serif",
                'body_font_size' => '14px', 'heading_font_weight' => '700',
                'layout_style' => 'contained', 'border_radius' => '8px', 'card_shadow' => '0 2px 8px rgba(46,204,113,0.12)',
            ],
            [
                'name'          => 'Ruby Red',
                'slug'          => 'ruby-red',
                'description'   => 'A passionate, vibrant ruby theme for confident brands.',
                'is_default'    => false,
                'is_active'     => true,
                'primary_color' => '#e0115f', 'secondary_color' => '#c00e52', 'accent_color' => '#ffd700',
                'text_color' => '#212529', 'heading_color' => '#111111', 'body_bg_color' => '#fff5f8',
                'header_bg_color' => '#ffffff', 'header_text_color' => '#212529',
                'footer_bg_color' => '#3d0a1e', 'footer_text_color' => '#f5b3cc',
                'copyright_bg_color' => '#2a0512', 'copyright_text_color' => '#ffffff',
                'button_bg_color' => '#e0115f', 'button_text_color' => '#ffffff', 'button_hover_bg_color' => '#c00e52',
                'border_color' => '#f5b3cc', 'sale_badge_bg' => '#ffd700', 'sale_badge_text' => '#000000',
                'font_family' => "'Roboto', sans-serif", 'heading_font' => "'Playfair Display', serif",
                'body_font_size' => '14px', 'heading_font_weight' => '700',
                'layout_style' => 'contained', 'border_radius' => '8px', 'card_shadow' => '0 4px 12px rgba(224,17,95,0.15)',
            ],
            [
                'name'          => 'Charcoal & Gold',
                'slug'          => 'charcoal-gold',
                'description'   => 'An elite black & gold theme for prestige and luxury brands.',
                'is_default'    => false,
                'is_active'     => true,
                'primary_color' => '#2c3e50', 'secondary_color' => '#1a252f', 'accent_color' => '#f39c12',
                'text_color' => '#ecf0f1', 'heading_color' => '#ffffff', 'body_bg_color' => '#1a1a2e',
                'header_bg_color' => '#2c3e50', 'header_text_color' => '#ecf0f1',
                'footer_bg_color' => '#0d1b2a', 'footer_text_color' => '#b8860b',
                'copyright_bg_color' => '#050a12', 'copyright_text_color' => '#8a6d0b',
                'button_bg_color' => '#f39c12', 'button_text_color' => '#000000', 'button_hover_bg_color' => '#d68910',
                'border_color' => '#b8860b', 'sale_badge_bg' => '#f39c12', 'sale_badge_text' => '#000000',
                'font_family' => "'Roboto', sans-serif", 'heading_font' => "'Playfair Display', serif",
                'body_font_size' => '14px', 'heading_font_weight' => '700',
                'layout_style' => 'full-width', 'border_radius' => '6px', 'card_shadow' => '0 4px 16px rgba(243,156,18,0.15)',
            ],
            [
                'name'          => 'Iceberg',
                'slug'          => 'iceberg',
                'description'   => 'A cool, refreshing blue theme for clean and modern stores.',
                'is_default'    => false,
                'is_active'     => true,
                'primary_color' => '#74b9ff', 'secondary_color' => '#48dbfb', 'accent_color' => '#fd79a8',
                'text_color' => '#2d3436', 'heading_color' => '#111111', 'body_bg_color' => '#f0faff',
                'header_bg_color' => '#ffffff', 'header_text_color' => '#2d3436',
                'footer_bg_color' => '#0c2d48', 'footer_text_color' => '#a8d8ea',
                'copyright_bg_color' => '#061a2e', 'copyright_text_color' => '#ffffff',
                'button_bg_color' => '#74b9ff', 'button_text_color' => '#ffffff', 'button_hover_bg_color' => '#5a9ed6',
                'border_color' => '#a8d8ea', 'sale_badge_bg' => '#fd79a8', 'sale_badge_text' => '#ffffff',
                'font_family' => "'Roboto', sans-serif", 'heading_font' => "'Jost', sans-serif",
                'body_font_size' => '14px', 'heading_font_weight' => '600',
                'layout_style' => 'contained', 'border_radius' => '10px', 'card_shadow' => '0 2px 8px rgba(116,185,255,0.12)',
            ],
            [
                'name'          => 'Terra Cotta',
                'slug'          => 'terra-cotta',
                'description'   => 'An earthy, rustic theme inspired by terracotta clay.',
                'is_default'    => false,
                'is_active'     => true,
                'primary_color' => '#e17055', 'secondary_color' => '#d35400', 'accent_color' => '#00b894',
                'text_color' => '#2d3436', 'heading_color' => '#111111', 'body_bg_color' => '#fdf6f0',
                'header_bg_color' => '#ffffff', 'header_text_color' => '#2d3436',
                'footer_bg_color' => '#3d1a0f', 'footer_text_color' => '#e8c4b8',
                'copyright_bg_color' => '#2a0f08', 'copyright_text_color' => '#ffffff',
                'button_bg_color' => '#e17055', 'button_text_color' => '#ffffff', 'button_hover_bg_color' => '#d35400',
                'border_color' => '#e8c4b8', 'sale_badge_bg' => '#00b894', 'sale_badge_text' => '#ffffff',
                'font_family' => "'Roboto', sans-serif", 'heading_font' => "'Jost', sans-serif",
                'body_font_size' => '14px', 'heading_font_weight' => '700',
                'layout_style' => 'contained', 'border_radius' => '10px', 'card_shadow' => '0 2px 8px rgba(225,112,85,0.12)',
            ],
            [
                'name'          => 'Monochrome',
                'slug'          => 'monochrome',
                'description'   => 'A timeless black & white theme for minimalist, classic brands.',
                'is_default'    => false,
                'is_active'     => true,
                'primary_color' => '#000000', 'secondary_color' => '#333333', 'accent_color' => '#666666',
                'text_color' => '#111111', 'heading_color' => '#000000', 'body_bg_color' => '#ffffff',
                'header_bg_color' => '#ffffff', 'header_text_color' => '#111111',
                'footer_bg_color' => '#111111', 'footer_text_color' => '#999999',
                'copyright_bg_color' => '#000000', 'copyright_text_color' => '#ffffff',
                'button_bg_color' => '#000000', 'button_text_color' => '#ffffff', 'button_hover_bg_color' => '#333333',
                'border_color' => '#cccccc', 'sale_badge_bg' => '#000000', 'sale_badge_text' => '#ffffff',
                'font_family' => "'Roboto', sans-serif", 'heading_font' => "'Jost', sans-serif",
                'body_font_size' => '15px', 'heading_font_weight' => '700',
                'layout_style' => 'contained', 'border_radius' => '0px', 'card_shadow' => '0 1px 4px rgba(0,0,0,0.06)',
            ],
        ];

        foreach ($themes as $theme) {
            // Add default admin panel colors if not set
            $theme['sidebar_bg_color'] = $theme['sidebar_bg_color'] ?? '#1e293b';
            $theme['sidebar_text_color'] = $theme['sidebar_text_color'] ?? '#ffffff';
            $theme['topbar_bg_color'] = $theme['topbar_bg_color'] ?? '#0f172a';
            $theme['admin_card_bg'] = $theme['admin_card_bg'] ?? '#ffffff';
            Theme::firstOrCreate(
                ['slug' => $theme['slug']],
                $theme
            );
        }
    }
}
