@extends('backEnd.layouts.master')
@section('title', 'Challans for Claim #' . $warrantyClaim->claim_number)
@section('content')
<div class="container-fluid">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h4>🧾 Challans for Claim #{{ $warrantyClaim->claim_number }}</h4>
        <a href="{{ route('admin.warranty.claims.show', $warrantyClaim) }}" class="btn btn-outline-secondary btn-sm">
            ← Back to Claim
        </a>
    </div>

    {{-- Claim Summary --}}
    <div class="card mb-3">
        <div class="card-body">
            <div class="row">
                <div class="col-md-4">
                    <strong>Product:</strong> {{ $warrantyClaim->product->name ?? 'N/A' }}<br>
                    <strong>Serial:</strong> {{ $warrantyClaim->warrantySale->serial_number ?? 'N/A' }}
                </div>
                <div class="col-md-4">
                    <strong>Customer:</strong> {{ $warrantyClaim->customer->name ?? 'N/A' }}<br>
                    <strong>Phone:</strong> {{ $warrantyClaim->customer->phone ?? 'N/A' }}
                </div>
                <div class="col-md-4">
                    <strong>Claim Status:</strong>
                    <span class="badge bg-info">{{ ucwords(str_replace('_', ' ', $warrantyClaim->status)) }}</span><br>
                    <strong>Type:</strong> {{ $warrantyClaim->issue_type ?? 'N/A' }}
                </div>
            </div>
        </div>
    </div>

    {{-- Challan Table --}}
    <div class="card">
        <div class="card-header">
            <h5 class="mb-0">All Challans ({{ $challans->count() }})</h5>
        </div>
        <div class="card-body p-0">
            <div class="table-responsive">
                <table class="table table-hover mb-0">
                    <thead class="table-light">
                        <tr>
                            <th>#</th>
                            <th>Challan No</th>
                            <th>Type</th>
                            <th>Generated By</th>
                            <th>Date</th>
                            <th class="text-center">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($challans as $index => $challan)
                        <tr>
                            <td>{{ $index + 1 }}</td>
                            <td><strong>{{ $challan->challan_no }}</strong></td>
                            <td>
                                @php
                                    $badgeClass = match($challan->challan_type) {
                                        'receive'         => 'badge-primary',
                                        'send_to_supplier' => 'badge-warning',
                                        'receive_return'   => 'badge-info',
                                        'delivery'         => 'badge-success',
                                        default            => 'badge-secondary',
                                    };
                                @endphp
                                <span class="badge {{ $badgeClass }}">{{ $challan->challan_type_label }}</span>
                            </td>
                            <td>{{ $challan->generatedBy->name ?? 'System' }}</td>
                            <td>{{ $challan->created_at->format('d M, Y h:i A') }}</td>
                            <td class="text-center">
                                <div class="d-flex gap-1 justify-content-center">
                                    <a href="{{ route('admin.warranty.challans.print', $challan) }}?autoprint=1" target="_blank"
                                       class="btn btn-sm btn-outline-primary" title="Print">
                                        🖨
                                    </a>
                                    <a href="{{ route('admin.warranty.challans.pdf', $challan) }}"
                                       class="btn btn-sm btn-outline-danger" title="Download PDF">
                                        📥
                                    </a>
                                </div>
                            </td>
                        </tr>
                        @empty
                        <tr>
                            <td colspan="6" class="text-center py-4 text-muted">
                                No challans generated yet for this claim.
                            </td>
                        </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection
