@php
    $mode = in_array($type ?? 'pos', ['pos', 'a4', 'a5'], true) ? ($type ?? 'pos') : 'pos';
    $shipping = $order->shipping;
    $paid = (float) ($order->paid_amount ?? 0);
    $due = max(0, (float) ($order->due_amount ?? ((float) $order->amount - $paid)));
    $subtotal = $order->orderdetails->sum(fn ($i) => (float) $i->sale_price * (int) $i->qty);
    $discount = $order->orderdetails->sum(fn ($i) => (float) ($i->product_discount ?? 0) * (int) $i->qty);
    $payments = $order->paymentHistory ?? collect();
@endphp
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Invoice {{ $order->invoice_display ?? $order->invoice_id }}</title>
<style>
*{box-sizing:border-box}html,body{margin:0;padding:0;background:#fff;color:#111827}body{font-family:'Courier New',Courier,monospace;line-height:1.35}.no-print{text-align:center;padding:10px;background:#222}.no-print button{margin:0 3px;padding:7px 15px;border:0;background:#fff;color:#000;cursor:pointer;font:12px 'Courier New',monospace}
.a4-document{width:100%;max-width:800px;margin:20px auto;padding:0 4px;font-size:14px}.a4-header{width:100%;border-collapse:collapse;margin-bottom:18px;border-bottom:1.5px solid #9CA3AF}.a4-header td{width:50%;padding:5px 0 10px;vertical-align:top}.a4-header td:last-child{text-align:right}.a4-title{font-size:22px;font-weight:700}.a4-meta{font-size:12px;line-height:1.45;color:#4B5563}.bill-to{margin-bottom:16px;border-bottom:1px solid #E5E7EB;padding-bottom:10px}.bill-to table{width:100%;border-collapse:collapse}.bill-to td{padding:2px 0;vertical-align:top}.bill-to td:first-child{width:130px}
.items-table{width:100%;border-collapse:collapse;margin-bottom:18px}.items-table th{border-top:1px solid #9CA3AF;border-bottom:1px solid #9CA3AF;background:#F3F4F6;color:#111827;text-align:left;padding:6px 4px}.items-table th:nth-child(1){width:50%}.items-table th:nth-child(2){width:10%;text-align:center}.items-table th:nth-child(3){width:15%;text-align:right}.items-table th:nth-child(4){width:10%;text-align:right}.items-table th:nth-child(5){width:15%;text-align:right}.items-table td{padding:4px;vertical-align:top}.items-table td.num{text-align:right;white-space:nowrap}.items-table td.qty{text-align:center}.product-name{font-weight:700}.product-details{padding-top:0!important;padding-bottom:7px!important;color:#4B5563;font-size:11px}
.financial-section{width:100%;display:flex;gap:5%;justify-content:space-between;margin-bottom:28px;page-break-inside:avoid;break-inside:avoid}.payment-history{width:55%;font-size:11px}.payment-history-title{font-weight:700;margin-bottom:4px}.payment-row{display:grid;grid-template-columns:22% 22% 36% 20%;gap:2px;border-bottom:1px solid #E5E7EB;padding:2px 0}.payment-row span:last-child{text-align:right;white-space:nowrap}.totals-table{width:40%;border-collapse:collapse;margin-left:auto;text-align:right}.totals-table td{padding:3px 4px}.totals-table td:first-child{text-align:left}.totals-table .rule td{border-top:1px solid #9CA3AF}.totals-table .grand td{border-top:1.5px solid #6B7280;font-weight:700}.terms{width:55%;font-size:11px;margin-bottom:42px;border-top:1px solid #9CA3AF;padding-top:5px}.terms strong{display:block;margin-bottom:3px}.signatures{display:flex;justify-content:space-between;page-break-inside:avoid;break-inside:avoid}.signature{width:200px;border-top:1px solid #6B7280;text-align:center;padding-top:5px;font-size:11px}
.pos-document{display:none;width:72mm;margin:0 auto;padding:5px;font:12px/1.35 'Courier New',Courier,monospace}.pos-center{text-align:center}.pos-bold{font-weight:700}.pos-line{border-top:1px solid #9CA3AF;margin:5px 0}.pos-double-line{border-top:1.5px solid #6B7280;margin:5px 0}.pos-flex{display:flex;justify-content:space-between;gap:4px}.pos-items{width:100%;border-collapse:collapse}.pos-items th{border-bottom:1px solid #9CA3AF;padding:2px 0;text-align:left}.pos-items th:nth-child(1){width:60%}.pos-items th:nth-child(2){width:15%;text-align:center}.pos-items th:nth-child(3){width:25%;text-align:right}.pos-items td{padding:3px 0 0;vertical-align:top}.pos-items td:nth-child(2){text-align:center}.pos-items td:nth-child(3){text-align:right;white-space:nowrap}.pos-details{padding:0 0 5px 10px!important;font-size:10px;color:#4B5563}.pos-total{font-weight:700;font-size:13px}.pos-terms{font-size:10px}
@media screen{body.print-pos .a4-document{display:none}body.print-a4 .pos-document,body.print-a5 .pos-document{display:none}body.print-a4 .a4-document,body.print-a5 .a4-document{display:block}body.customer-page .a4-document{display:block}}
@media print{.no-print{display:none!important}.a4-document,.pos-document{margin:0}.items-table thead{display:table-header-group}.items-table tr,.financial-section,.signatures{page-break-inside:avoid;break-inside:avoid}body.print-a4 .a4-document,body.print-a5 .a4-document{display:block}body.print-a4 .pos-document,body.print-a5 .pos-document{display:none}body.print-pos .a4-document{display:none}body.print-pos .pos-document{display:block}@page{size:A4 portrait;margin:10mm}}
@media print{body.print-a5 .a4-document{font-size:11px;margin:0;padding:0}body.print-a5 .a4-title{font-size:18px}body.print-a5 .a4-header{margin-bottom:10px}body.print-a5 .a4-header td{padding-bottom:5px}body.print-a5 .a4-meta,body.print-a5 .payment-history,body.print-a5 .terms,body.print-a5 .signature{font-size:9px}body.print-a5 .bill-to{margin-bottom:9px}body.print-a5 .items-table th,body.print-a5 .items-table td{padding:3px 2px}body.print-a5 .product-details{font-size:9px;padding-bottom:5px!important}body.print-a5 .financial-section{margin-bottom:16px}body.print-a5 .terms{margin-bottom:25px}body.print-a5 .signature{width:130px}}
@media print{body.print-pos{width:80mm;margin:0;padding:0}body.print-pos .a4-document{display:none!important}body.print-pos .pos-document{display:block!important;width:72mm;margin:0;padding:5px}}
@media print and (max-width:155mm){.a4-document{font-size:11px;margin:0;padding:0}.a4-title{font-size:18px}.a4-header{margin-bottom:10px}.a4-header td{padding-bottom:5px}.a4-meta,.payment-history,.terms,.signature{font-size:9px}.bill-to{margin-bottom:9px}.items-table th,.items-table td{padding:3px 2px}.product-details{font-size:9px;padding-bottom:5px!important}.financial-section{margin-bottom:16px}.terms{margin-bottom:25px}.signature{width:130px}@page{size:A5 portrait;margin:6mm}}
@media print and (max-width:90mm){html,body{width:80mm;margin:0;padding:0}.a4-document{display:none!important}.pos-document{display:block!important;width:72mm;margin:0;padding:5px}@page{size:80mm auto;margin:0}}
</style></head>
<body class="print-{{ $mode }}{{ !empty($customerPage) ? ' customer-page' : '' }}">
<div class="no-print"><button onclick="setMode('pos')">Print POS</button><button onclick="setMode('a4')">Print A4</button><button onclick="setMode('a5')">Print A5</button><button onclick="window.close()">Close</button></div>
<main class="a4-document">
<table class="a4-header"><tr><td><span class="a4-title">{{ $generalsetting->name ?? config('app.name') }}</span><br>@if($contact?->address){{ $contact->address }}<br>@endif @if($contact?->phone)Phone: {{ $contact->phone }}<br>@endif @if($contact?->email)Email: {{ $contact->email }}@endif</td><td><span class="a4-title">SALES INVOICE</span><br><span class="a4-meta"><strong>Invoice No:</strong> {{ $order->invoice_display ?? $order->invoice_id }}<br><strong>Date:</strong> {{ optional($order->created_at)->format('d M Y') }}@if($order->user?->name)<br><strong>Sales Rep:</strong> {{ $order->user->name }}@endif</span></td></tr></table>
<section class="bill-to"><strong>BILL TO:</strong><table><tr><td>Customer Name:</td><td>{{ $shipping->name ?? $order->customer?->name ?? '—' }}</td></tr><tr><td>Phone Number:</td><td>{{ $shipping->phone ?? $order->customer?->phone ?? '—' }}</td></tr><tr><td>Address:</td><td>{{ trim(($shipping->address ?? '').(($shipping->area ?? '') ? ', '.$shipping->area : '')) ?: '—' }}</td></tr></table></section>
<table class="items-table"><thead><tr><th>ITEM DESCRIPTION &amp; DETAILS</th><th>QTY</th><th>PRICE</th><th>DISC</th><th>TOTAL</th></tr></thead><tbody>
@foreach($order->orderdetails as $item)
@php $salePrice=(float)$item->sale_price;$lineTotal=$salePrice*(int)$item->qty;$itemDiscount=(float)($item->product_discount??0);$warranty=$item->warrantySale;$meta=[];if($item->product_size&&!is_numeric($item->product_size))$meta[]='Size: '.$item->product_size;if($item->size?->sizeName)$meta[]='Size: '.$item->size->sizeName;if($item->color?->colorName)$meta[]='Color: '.$item->color->colorName; @endphp
<tr><td><span class="product-name">{{ $loop->iteration }}. {{ $item->product_name }}</span></td><td class="qty">{{ $item->qty }}</td><td class="num">৳{{ number_format($salePrice,2) }}</td><td class="num">{{ $itemDiscount>0?'৳'.number_format($itemDiscount,2):'—' }}</td><td class="num">৳{{ number_format($lineTotal,2) }}</td></tr>
@if($meta||$warranty?->serial_numbers||($warranty&&$warranty->warranty_days>0)||(($item->supplier_warranty_days??0)>0))<tr class="product-details"><td colspan="5">@if($meta)* {{ implode(' | ',$meta) }}@endif @if($warranty?->serial_numbers){{ $meta?' | ':'' }}* SL: {{ implode(', ',$warranty->serial_numbers) }}@endif @if($warranty&&$warranty->warranty_days>0){{ ($meta||$warranty->serial_numbers)?' | ':'' }}* Warranty: {{ $warranty->warranty_days }}D @if($warranty->warranty_end_date)| Exp: {{ $warranty->warranty_end_date->format('d M Y') }}@endif @endif @if(!$warranty&&($item->supplier_warranty_days??0)>0)* Warranty: {{ $item->supplier_warranty_days }}D@endif</td></tr>@endif
@endforeach</tbody></table>
<section class="financial-section"><div class="payment-history"><div class="payment-history-title">PAYMENT HISTORY / GATEWAY LOG</div>@forelse($payments as $paymentRecord)<div class="payment-row"><span>{{ optional($paymentRecord->created_at)->format('d M Y') }}</span><span>{{ $paymentRecord->payment_method??'Payment' }}</span><span>{{ $paymentRecord->trx_note?:'—' }}</span><span>৳{{ number_format((float)$paymentRecord->amount,2) }}</span></div>@empty<div>No payments recorded</div>@endforelse</div><table class="totals-table"><tr><td>Gross Subtotal</td><td>৳{{ number_format($subtotal,2) }}</td></tr>@if($discount>0)<tr><td>Total Discount</td><td>-৳{{ number_format($discount,2) }}</td></tr>@endif @if((float)$order->shipping_charge>0)<tr><td>Shipping</td><td>+৳{{ number_format($order->shipping_charge,2) }}</td></tr>@endif <tr class="grand"><td>Total Invoice Value</td><td>৳{{ number_format((float)$order->amount,2) }}</td></tr><tr class="rule"><td>Total Paid (To Date)</td><td>৳{{ number_format($paid,2) }}</td></tr><tr class="grand"><td>Net Balance Due</td><td>৳{{ number_format($due,2) }}</td></tr></table></section>
<div class="terms"><strong>TERMS &amp; CONDITIONS:</strong>Goods sold are not returnable / exchangeable. Keep this invoice for warranty claims.</div><div class="signatures"><div class="signature">Customer Signature</div><div class="signature">Authorized Store Signature</div></div>
</main>
<main class="pos-document"><div class="pos-center pos-bold" style="font-size:15px">{{ $generalsetting->name??config('app.name') }}</div><div class="pos-center">{{ $contact?->address }}{{ $contact?->phone?' | '.$contact->phone:'' }}</div><div class="pos-double-line"></div><div class="pos-flex"><span>Inv: {{ $order->invoice_display??'#'.$order->invoice_id }}</span><span>{{ optional($order->created_at)->format('d-m-Y') }}</span></div><div class="pos-line"></div><table class="pos-items"><thead><tr><th>ITEM / DETAILS</th><th>QTY</th><th>PRICE</th></tr></thead><tbody>
@foreach($order->orderdetails as $item)@php $w=$item->warrantySale;$m=[];if($item->product_size&&!is_numeric($item->product_size))$m[]='Size: '.$item->product_size;if($item->size?->sizeName)$m[]='Size: '.$item->size->sizeName;if($item->color?->colorName)$m[]='Color: '.$item->color->colorName;@endphp<tr><td>{{ $item->product_name }}</td><td>{{ $item->qty }}</td><td>{{ number_format((float)$item->sale_price*(int)$item->qty,0) }}</td></tr>@if($m||$w?->serial_numbers||($w&&$w->warranty_days>0)||(float)($item->product_discount??0)>0)<tr><td colspan="3" class="pos-details">@if($m)* {{ implode(' | ',$m) }}<br>@endif @if($w?->serial_numbers)* SL: {{ implode(', ',$w->serial_numbers) }}<br>@endif @if($w&&$w->warranty_days>0)* Wnty: {{ $w->warranty_days }}D<br>@endif @if((float)($item->product_discount??0)>0)* Disc: ৳{{ number_format((float)$item->product_discount,0) }}@endif</td></tr>@endif @endforeach
</tbody></table><div class="pos-line"></div><div class="pos-flex pos-total"><span>TOTAL BDT:</span><span>{{ number_format((float)$order->amount,0) }}</span></div><div class="pos-flex"><span>PAID:</span><span>{{ number_format($paid,0) }}</span></div>@if($payments->isNotEmpty())<div class="pos-line"></div><div class="pos-bold">PAYMENTS:</div>@foreach($payments as $p)<div class="pos-flex"><span>{{ optional($p->created_at)->format('d/m') }} {{ $p->payment_method??'PAY' }}</span><span>{{ number_format((float)$p->amount,0) }}</span></div>@endforeach @endif<div class="pos-line"></div><div class="pos-flex pos-bold"><span>DUE BALANCE:</span><span>{{ number_format($due,0) }}</span></div><div class="pos-line"></div><div class="pos-terms">Terms: Warranty claims require this slip and valid serial number.</div><div class="pos-double-line"></div><div class="pos-center pos-bold">THANK YOU!</div></main>
<style id="invoice-page-rule" media="print"></style><script>function setMode(mode){document.body.classList.remove('print-pos','print-a4','print-a5');document.body.classList.add('print-'+mode);setPageRule(mode);window.print()}function setPageRule(mode){var size=mode==='pos'?'80mm auto':(mode==='a5'?'A5 portrait':'A4 portrait');var margin=mode==='pos'?'0':(mode==='a5'?'6mm':'10mm');document.getElementById('invoice-page-rule').textContent='@page{size:'+size+';margin:'+margin+'}'}setPageRule(@json($mode));window.addEventListener('load',function(){if(new URLSearchParams(location.search).get('autoprint')==='1')setTimeout(function(){window.print()},250)})</script></body></html>
